export const FETCH_REGISTRATION_ERROR = 'FETCH_REGISTRATION_ERROR'
export const FETCH_REGISTRATION_PENDING = 'FETCH_REGISTRATION_PENDING'
export const FETCH_REGISTRATION_SUCCESS = 'FETCH_REGISTRATION_SUCCESS'
export const FETCH_REGISTRATION_SEARCH = 'FETCH_REGISTRATION_SEARCH'